### PR TITLE
Remove extra line in README

### PR DESCRIPTION
**Pull request by rgee0**
Signed-off-by: Richard Gee <richard@technologee.co.uk>

### CODE REVIEW

**Comment by alexellis** [comment]
So this is the Docker image from Martin, we should have seen a label?

**Comment by rgee0** [comment]
Right, first-timer?

**Comment by alexellis** [comment]
From the debug page:

Payload:

```
    "author_association": "NONE",
```

Response:

```
Content-Length: 245
Content-Type: application/json
Date: Wed, 04 Jul 2018 18:57:31 GMT
X-Call-Id: 84ebebab-b349-46f9-9ce8-14393769dcea
X-Duration-Seconds: 1.564395
X-Start-Time: 1530730649869459743
Body
2018/07/04 18:57:30 alexellis alexellis [alexellis moby openfaas rgee0 openfaas-incubator Subsurface-divelog]
Rate limiting github.Rate{Limit:5000, Remaining:4999, Reset:github.Timestamp{2018-07-04 19:57:31 +0000 UTC}}
Things look OK right now.

```

**Comment by martindekov** [comment]
That bot was not with the changes by the end of the day i redid the whole GET.md couple of times and downloaded your bot by mistake and pushed your derek instead of mine.I will try to redo the thing one last time but last night when i tried to update the bot with master branch i messed something up so i cannot push it to my fork with the changes i did.I will wait for Ivana to come and help me out.

**Comment by rgee0** [comment]
This was raised to test Derek and was never meant to be merged, hence can be closed.

**Comment by alexellis** [comment]
Thanks

**Pull request closed without merging**
